### ISSUE TITLE
module requiring itself

### ISSUE THREAD

**Issue by gilbertohasnofb** [JTPond/python-requirements#1]
Would there be a way of not adding a module itself to its own `requirement.txt`? This happens when there are some self-imports, for instance when using a `setup.py` and importing the module into it to, say, get the `__version__` of the module. Perhaps the best approach would be to not add any local modules into the requirements, since those are obviously satisfied.

**Comment by gilbertohasnofb** [comment]
One more idea: it would also be best to exclude all modules from the standard library since they are bundled with every Python installation and are not available through pip. Automated tools such as Travis-Cl will fail to build if those modules are listed in the requirements, since it automatically tries to use pip to download them and fails. It's also common for users to execute ` pip install -r requirements.txt` when manually installing a library.

**Comment by gilbertohasnofb** [comment]
Here is a list of all modules: https://docs.python.org/3.7/py-modindex.html

**Comment by JTPond** [comment]
Thanks for your feedback, I really appreciate it. I think I've addressed both of your comments in the current master branch. I'd be interested to know if this fixes your issues before I publish on apm. I'll leave the issue open for now.

**Comment by gilbertohasnofb** [comment]
@JTPond thank you so much for taking a look at this. I tried testing it but Atom hangs when I execute your package now, and the `requirements.txt` file it creates is empty. Have you experienced anything like this in your tests?

**Comment by JTPond** [comment]
I have not seen that. I will definitely get back to it soon. Thanks for taking a look!

**Comment by gilbertohasnofb** [comment]
I am using atom 1.40.1 on Linux Mint 18.3 64-bit, if that helps. This behaviour happens even in the most simple projects. For instance, I created a file with a single line `import random` and as soon as the file `requirements.txt` is created, Atom hangs.

**Comment by JTPond** [comment]
Alright, I was able to recreate your issue immediately and I'm amazed it didn't appear in earlier testing. Anyway, try now. Keep in mind, because I'm excluding standard modules, a single file with `import random` will still produce an empty req.txt

Thanks again for the feedback

**Comment by gilbertohasnofb** [comment]
Great, thanks for the quick fix!

>  Keep in mind, because I'm excluding standard modules, a single file with import random will still produce an empty req.txt

Yeah, that was the idea: testing a minimal case in order to see if any of the other imports were breaking the package.

So I tested it and it works wonderfully well, it excludes standard and local modules exactly as one would expect. The only small bug I found is that if you run your package on a repo which already has a `requirements.txt` file, the package is appending the list to it instead of overwriting that file. I think overwriting should be the default behaviour, particularly because one might run it several times while developing as you import new libraries into a project.

**Comment by JTPond** [comment]
I think you're right. I've pushed that now. It looks like it works good. If it's good on your end, I'll close the issue and publish to apm.

Thanks for all your help!

**Comment by gilbertohasnofb** [comment]
Just tested it, it's all good on my side. Thank you so much for all the improvements and fixes, this package will be super handy!

**Comment by JTPond** [comment]
No problem, and I sure hope so!
