### ISSUE TITLE
better handling of commas and semicolons

### ISSUE THREAD

**Issue by gilbertohasnofb** [JTPond/python-requirements#3]
I have a code which containes the one liner `import pdb; pdb.set_trace()`. Your package adds `pdb;` to the `requirements.txt`. Not only the inclusion of the semicolon is problematic but also is a built-in library (listed in https://docs.python.org/3.7/py-modindex.html ).

Another import that seems to confuse this package is `import math, random, numpy`. It adds `math,` to the `requirements.txt`, but weirdly enough not `random,`.

**Comment by JTPond** [comment]
Okay, I should be able to come up with a fix for the pbd problem. I'd never actually seen that pattern before. Once the semicolon is removed it should be skipped by the built-in package filter. As for multiple comma separated modules, I'm unsure. It says in the readme that it's not a supported pattern because it's against [pep8 ](https://www.python.org/dev/peps/pep-0008/#imports). But I'll look into it. 

Thanks for the comment

**Comment by gilbertohasnofb** [comment]
Thanks for taking a look into this. I agree that the semicolon pattern is the most important one since that is what PEP recommends for that specific module. As for the comma separated imports, I understand that that is not what PEP8 recommends, but it is still supported by Python and could be fairly simple to implement. But it's absolutely not a big deal if you decide against it (I myself never use it, just discovered it by accident).

**Comment by JTPond** [comment]
I've got special character handling done, and tested against the pdb pattern. I also decided to go ahead and add the comma support. I don't know if it was ever pep complaint, but I know it sure was common for awhile. I did a fair amount of testing on my side, but would you mind pulling master and checking against the code that brought it to you attention? I'd really appreciate it.

**Comment by gilbertohasnofb** [comment]
That's great, thanks for implementing this. I just tested the new release version `d2228511` and it seems that the comma problem has been solved, and neither the `math` nor the `random` standard library modules are listed. I did come across two new bugs though.

1) I have now an entry `pdbset_trace` (but not a `pdb`, which is good). 
2) if a comment in an import line contains a comma, your package now considers every word in that comment as a package. E.g.: `import random  # this is part of the standard library, but it's not math` produces:
```
this
is
part
of
the
standard
library
but
its
not
```
(note how it correctly omits the `random` package but also the `math` word which I just randomly threw into the comment for testing)

**Comment by gilbertohasnofb** [comment]
And just to clarify: if a comment doesn't have a comma, your package behaves as expected. So there is no problem with `import random  # super useful package`

**Comment by JTPond** [comment]
So I tested the issue with pbdtrace being added and the only way I could recreate it was with the semicolon replaced with a comma `import pdb, pdb.set_trace()` inplace of `import pdb; pdb.set_trace()`. If that's not what happened, let me know, but I didn't see that issue. I did push a fix for the inline comments to master, though. Let me know if you see any more issues and thanks again for helping out.

**Comment by gilbertohasnofb** [comment]
No worries, I am happy to help. I think I managed to find the issue, this seems to happen only when there is a comment containing a comment after the set_trace() function, as in `import pdb; pdb.set_trace()  # foo, bar`.

**Comment by JTPond** [comment]
You're right, that would do it, which means it's still not fixed. Good catch. That's what I get for separating those two issues in my mind

**Comment by gilbertohasnofb** [comment]
Great! I am happy to test the final version, but I think this is the only problematic case I could find. Again, many thanks for fixing these.

**Comment by JTPond** [comment]
Okay, I'm pretty confident with this one. I realized I should just trim off inline comments before processing the line, anyway. But it passed all the examples you've brought up so far.

**Comment by gilbertohasnofb** [comment]
Yes, I just tested the new version and I see no issues with the project I was testing it with. Thank you so much for the fixes!

**Comment by JTPond** [comment]
Great! Thanks for all your testing. Closing the issue.
